openapi: 3.0.3

info:
  title: Board
  description: Board
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local Develpoment

paths:
  /api/board:
    get:
      summary: List all Board
      operationId: getBoard
      tags:
        - board
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Board"
        default:
          description: FAIL

  /api/board/write:
    post:
      summary: Write Board
      operationId: postBoard
      tags:
        - board
      requestBody:
        description: Write Board
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                contents:
                  type: string
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Board"
        '400':
          description: FAIL

  /api/board/{boardIdx}:
    get:
      summary: List Board
      operationId: getOneBoard
      tags:
        - board
      parameters:
        - name: boardIdx
          in: path
          required: true
          description: Board id
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Board"
        default:
          description: FAIL

    put:
      summary: Update Board
      operationId: updateBoard
      tags:
        - board
      parameters:
        - name: boardIdx
          in: path
          required: true
          description: Board id
          schema:
            type: integer
      requestBody:
        description: Update Board
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                contents:
                  type: string
                boardIdx:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Board"
        '400':
          description: FAIL

    delete:
      summary: Delete Board
      operationId: removeBoard
      tags:
        - board
      parameters:
        - name: boardIdx
          in: path
          required: true
          description: Board id
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Board"
        '404':
          description: FAIL

components:
  schemas:
    Board:
      type: object
      properties:
        board_idx:
          type: integer
          format: int64
        title:
          type: string
        contents:
          type: string
        hit_cnt:
          type: integer
          format: int64
        creator_id:
          type: string
        created_datetime:
          type: string
        updater_id:
          type: string
        updated_datetime:
          type: string